INTI-CMNB/KiBot

kibot/mcpyrate/coreutils.py

There is an error that prevents kibot from starting when `sys.path` contains a parent of another path (issue #29).
For example, if `sys.path` contains:
```
/home/user/.local/
/home/user/.local/lib/python3.8/site-packages/
```
The path resolution algorithm will find the first one first and then fail to find the package there (which makes sense, because that's not a Python package directory). This PR sorts the path names by length, so a longer path will always match before a shorter one.

Fix import issue when a shorter base path matches before a shorter one

---

Dockerfile

This is a fix for the following error when executing as a github action:
`/entrypoint.sh: line 144: /usr/bin/kicad-git-filters.py: No such file or directory`
This was reported in #37

Added kicad-git-filters installation to Dockerfile

---

kibot/kicad/v5_sch.py

Hi,
I just stumbled across KiBot and I have to admit that I am really impressed by the amount of work you've put into the project. And it has some really good (and extensive(!) documentation), which is usually something that a lot of open source projects are lacking. Many thanks for that! :)
While playing a bit with KiBot, I stumbled across a (what I believe to be) bug. The issue can be triggered by some libraries from snapeda.com (e.g this one: https://www.snapeda.com/parts/TS3A27518EPWR/Texas%20Instruments/view-part/). 
I've seen that KiBot assumes that the *.lib ends with a `#End Library` token. But (some) libs from SnapEDA use the token `# End Library` (with a space between `#` and `E`), causing KiBot to fail with:
```
ERROR:Trace stack: (kibot.kibot.error - error.py:33)
File …
```

be more tolerant when parsing libraries

---

README.md
docs/README.in
kibot/fil_rot_footprint.py

Thanks for considering this PR implementing the solution proposed in #60.
Firstly, it was very gratifying to see the resulting correctly rotated part on the PCB:NG placement view. No manual rotation required. Yay.
One extra feature that I found necessary was the ability to select all parts on the bottom of the board, because I didn't want any rotation applied to the top parts.
I implemented this by appending the board `side` ("_top" or "_bottom") to the footprint name prior to matching. A user can match on "_bottom" or "_top" to select components on a single side. Because it's all one `match_string` users can select components of a specific type on a side, too, using "^MyFootprint.*_top", for instance.
This is a potentially breaking change, depending on how users have created their match …

Added invert_bottom and side selection

---

kibot/kicad/config.py

~~To be honest I don't understand all the code (yet), but with this change `$ kibot print_sch` works together with Kicad 6.0, because the `Junction`s does not seem to have UUIDs.~~
Commit 7bdc1f5 fixes a crash in case the `config_common.json` config file is present and contain a `vars` in `environment`, but the value is `None` (null). This is the case at least on a freshly installed Kicad on Linux/Ubuntu.

KiCad 6: Catch environment.vars==None case 

---

kibot/kicad/v6_sch.py

Fixes  #144.
I don't know how to handle the "lib_name" symbol so I just store it in "schlib_name" for now.

Handle lib_name in symbol instance

---

kibot/config_reader.py
kibot/out_kibom.py
kibot/out_report.py

This allows using environment variable expansion in paths for importing outputs from other configuration files or specifying the KiBoM configuration file.
For example in "import" section:
```
import:
- file: '${KIBOT_CFG}/config.yaml'
- file: '~/some_config.yaml'
```

Allow expansion of environment variables in paths

---

kibot/out_report.py

This fixes the OAR calculation used in the design report. OAR was calculated as pad_size - toolsize, resulting in a value that was twice what it should have been. Now it should be calculated correctly as (pad_size - toolsize) / 2.

fix OAR calculation for design report

---

README.md
docs/samples/generic_plot.kibot.yaml
kibot/out_any_sch_print.py

Support exporting the root schematic only as in KiAuto without the `--all_pages` option. Thanks.

Added in SCH PDF Print: An all_pages option

---

kibot/kiplot.py

It seems that KiBot prints excessive and somewhat misleading info to the console while exporting schematic files:
```
Using PCB file: the/path/to/the/file.kicad_pcb # may confuse users
- 'Export schematic (sch) [pdf_sch_print]'     # may differ, based on YAML configs
```
This would not happen when exporting PCB layout files as `solve_schematic` does not print the `Using SCH file` hint to the console if `not schematic and a_board_file` holds. Thus, for symmetry and reducing potentially misleading wordings, I prefer suppress this info message. The hint would still be dumped when debug level is set. Thanks.

Suppress an excessive info message to console

---

kibot/misc.py

This small fix changes the user agent string to what would be reported by a recent version of Firefox.
Previously KiBot pretended to be a rather old version of Firefox which for some reason creates issues when trying to download datasheets from certain servers:
```
WARNING:(W048) Failed to download `https://media.digikey.com/pdf/Data%20Sheets/Samsung%20PDFs/CL05C100JB5NNNC_Spec.pdf` (kibot - out_download_datasheets.py:75)
WARNING:(W048) Timeout during download `https://www.phoenixcontact.com/us/products/1999000/pdf` (kibot - out_download_datasheets.py:69)
WARNING:(W048) Timeout during download `https://www.phoenixcontact.com/us/products/1847479/pdf` (kibot - out_download_datasheets.py:69)
WARNING:(W048) Timeout during download `https://www.phoenixcontact.com/us/products/1843855/pdf` …
```

Update user agent string to pretend being a recent version of Firefox

---

kibot/out_download_datasheets.py

This is just a small fix that prevents KiBot from crashing if an 'SSLError' is raised while downloading datasheets, e. g. this would happen if the server certificate expired. Previously this would cause KiBot to crash, now a warning is shown.

catch possible SSLError when downloading datasheets

---

README.md
docs/samples/generic_plot.kibot.yaml
kibot/out_position.py

KiCAD's generated position files have 6 digit mantissa. Some users would like to have the position file(s) generated in the same way than KiCAD. This option makes that possible while keeping the default behaviour of using 4 digits mantissa.
Signed-off-by: Kevin Joly <kevin.joly@armadeus.com>

[Position] Add "right_digits" option

---

kibot/kiplot.py

this should be self explantory

don't show warning if footprint has attribute "not in schematics"

---

kibot/out_report.py

Uses duck-typing for the test instead of requiring the type be one of a few specific instances. This fixes the following error I get with kicad v7.0.4: `TypeError: float() argument must be a string or a real number, not 'VECTOR2I'`

Fix type error

---

kibot/kicad/v6_sch.py

Hi @set-soft,
Firstly, thank you for all your hard work on kibot and associated tools.
The intention of this pull request is to add handling of custom unit names, as described in: 
https://docs.kicad.org/7.0/en/eeschema/eeschema.html#creating-and-editing-symbols
(can't link to the exact subsection, search for 'Set Unit Display Name')
Kibot (v1.6.3) gives the following error if a symbol with a custom unit name is used:
```ERROR:Unknown symbol attribute `[Symbol('unit_name'), '<UNIT NAME>']` (kibot.gs - gs.py:731)```
The sexpr formatting isn't described in: https://dev-docs.kicad.org/en/file-formats/sexpr-schematic/
But is pretty basic: `(unit_name "<UNIT NAME>")` 
I have added handling of this field, and stored it in the LibComponent object.
A minimum reproducable project can be found …

Handle Symbol Unit Custom Names

---

kibot/kicad/v6_sch.py

Hi @set-soft,
I was getting the following error type:
```ERROR:While loading `/home/ac/work/kibot-heirachal-test/kibot-heirachal-test.kicad_sch` (kibot.gs - gs.py:751)
ERROR:Missing R symbol instance for `/2f7bf752-fced-400e-aa47-c202d1ff4cb6/91fd3c38-308c-4a0d-8dce-5c7dfcc46162/a5130e09-dadf-45c6-a20a-45a2acdafc58/a1b591db-7eff-4e8b-9266-52a5fd7ed10d` (kibot.gs - gs.py:751)```
When working with a sch tree akin to the following:
where A and A1 are copies of the same sheet.
Example project [here](https://github.com/Andrew-Collins/kibot-hierarchical-test).
I tracked this down to the `ori` path of each sheet being based on the parent's non-`ori` path.
This caused the uuid/path of the sheet to get out of whack with the `instances` fields in the `sch` file.
So this PR just bases the `ori` path …

Fix handling of hierarchical branches with a depth >2 

---

kibot/kiplot.py

When running kibot, we check if a path exists. However, this seems to fail with for example symlinks, resulting in the following error.
```
Using SCH file: 1.kicad_sch
- 'Records information about the current run.' (info) [info]
Traceback (most recent call last):
File "/usr/bin/kibot", line 33, in <module>
sys.exit(load_entry_point('kibot==1.6.3', 'console_scripts', 'kibot')())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/kibot/__main__.py", line 520, in main
generate_outputs(outputs, args.target, args.invert_sel, args.skip_pre, args.cli_order, args.no_priority,
File "/usr/lib/python3/dist-packages/kibot/kiplot.py", line 527, in generate_outputs
_generate_outputs(outputs, targets, invert, skip_pre, cli_order, no_priority, dont_stop) …
```

kiplot: Allow output dir to exist

---

.github/logToCs.py
.github/workflows/pre-commit.yml
.pre-commit-config.yaml

@set-soft Best wishes for 2024!
I've been setting up a pre-commit github action on my projects with a script to convert the messages to code annotations on github.
I've also updated the hook versions (`pre-commit autoupdate`) which reveal some new "Issues":
- Spelling;
- Linter messages.
The spelling could be fixed in this PR or a separate PR.
As far as the linter messages are concerned, it needs to be decided if they will be changed in the code or excluded in the `setup.cfg`.
A limited number of Github Pull Request code annotations are visible in the Summary of the workflow and in the Files changed tab of a pull request (annotations of files that were not changed are at the bottom of the tab).
I hope you find this useful

Flow/pre commit action - upgrade pre-commit hooks

---

CHANGELOG.md
kibot/out_diff.py
kibot/out_kiri.py

When kibot creates a worktree, which in some cases creates a new branch
or uses an existing branch. This branch may be old and stale, and often
not what is expected.
Instead, avoid the issue entirely, by never creating anything that could
need cleaning up, by creating a detached worktree.
Fixes #556

[Diff][Fixed] Worktree's can leave junk branches

---

CHANGELOG.md
kibot/pre_update_xml.py

It is quite common, to add footprints to a PCB, without adding it to the schematic. Think Logo's or 'duplicate' connectors etc. KiCad has a flag called 'Not in schematic' for this purpose. Lets check if this flag is set in the PCB, and ignore any errors from this if applicable.
Fixes: #558.

pre_update: Honor 'board_only' (Not in schematic) footprint property.

---

docs/samples/generic_plot.kibot.yaml
docs/source/configuration/outputs/dxf.rst
docs/source/configuration/outputs/gerber.rst
docs/source/configuration/outputs/hpgl.rst
docs/source/configuration/outputs/pdf.rst
docs/source/configuration/outputs/ps.rst
docs/source/configuration/outputs/svg.rst
kibot/out_any_layer.py

Continuation of #517 
Prevents markdown from detecting and formatting it as math

Add backticks around custom_reports docs to improve layout

---

kibot/bom/xlsx_writer.py

When generating BoM in xlsx format the color reference is not generated when row_colors is enabled but col_colors is disabled. This change generates the color reference if either col_colors or row_colors are enabled.

[BoM][Fixed] Generate color ref for xlsx output

---

kibot/out_svg.py

* Add the same flag from the PDF export for using the aux origin for the export.
I hit this while trying to integrate an exported layer into build123d, and found that having the aux origin used for the SVG as well was the most reliable way to get things positioned to match the P&P exports, etc.

[SVG Export][Added] Flag for using aux origin

---

kibot/pre_draw_fancy_stackup.py

This PR adds a new preflight (fancy_stackup), which adds an alternate stackup drawing to the existing one. The main features are:
- Stackup information as a table, column order can be set with the preflight configuration
- Automatic parsing of via type (buried/normal and microvia) and via pairs (symmetric across the stackup), and optionally drawn in the stackup table
- Optional note at the bottom of the stackup table
- Many configurable parameters, such as spacing between columns and layers, spacing and size of vias, etc.
- Gerber column can be plotted as the full name or extension only
Example with thru, buried via pairs, single buried via, microvia pairs and single microvia. Stackup table columns are inspired from Altium's Draftsman stackup tool.

[Fancy Draw Stackup][Added] Alternative Stackup Drawing

---

kibot/optionable.py
kibot/out_pcb_print.py

This PR sets the `make_safe` flag option to `False` for the `expand_sheet_patterns` function of PCB Print to allow colons in `layer_var` and `sheet` text expansions. Previously, the colons were replaced with `_`.
Example with `layer_var`:
Before:
After

[PCB Print][Fixed] Allow colons in sheet and layer_var expansions

---

kibot/out_bom.py

This PR fixes the get_csv_separator() function for the BoM class, which raises the error:
`'BoM' object has no attribute 'csv'`

[Fix] fix get_csv_separator() function for BoM class

---

kibot/pre_include_table.py

This PR fixes incorrect mapping between output and CSV files for the Include Table preflight. Previously, the preflight parameters of the last provided output were used for all outputs, for example here `csv_testpoints_bottom` options were used for the `csv_testpoints_top` output.
```
include_table:
outputs: 
- name: 'csv_testpoints_top'
text_alignment: 'left'
invert_columns_order: False
border_width: 0.2
header_rule_width: 0.2
horizontal_rule_width: 0
vertical_rule_width: 0
top_rule_width: 0
- name: 'csv_testpoints_bottom'
text_alignment: 'right'
invert_columns_order: True
border_width: 0.2
header_rule_width: 0.2
horizontal_rule_width: 0
vertical_rule_width: 0
top_rule_width: 0
```

[Fix][Include Table] Use correct output parameters w.r.t. CSV files

---

kibot/out_pcb_print.py

This PR fixes wrong index for group name detection of the "Include Image" feature. Previously it used index 13, which should be index 12 as the name changed from `_kibot_image_*` to `kibot_image_*`

[Fix][Include Image] Wrong index for group name detection

---

docs/source/configuration/outputs/ExcellonOptions.rst
docs/source/configuration/outputs/Gerb_DrillOptions.rst
kibot/out_any_drill.py
kibot/out_excellon.py

This PR adds the `generate_drill_files` option (default `True`) to the `gerb_drill` and `excellon` outputs. This is useful when one wants to only generate the drill map without drill files.

[Drill Output][Added] Option to omit generation of drill files

---

kibot/bom/bom.py
kibot/bom/columnlist.py

This PR adds a new column `Net Label`, which is similar to to `Net Name` but without the path. Only displays the Net Label given in the schematic. For example, for the nets:
```
/Project Architecture/MCU - IOs/MOTOR_ENABLE
/Project Architecture/MCU - IOs/MOTOR_HIZ
/Project Architecture/MCU - IOs/MOTOR_FAULT
/Project Architecture/MCU - IOs/DRV_SCLK
/Project Architecture/MCU - IOs/DRV_MISO
```
Net label would be:
```
MOTOR_ENABLE
MOTOR_HIZ
MOTOR_FAULT
DRV_SCLK
DRV_MISO
```
If there is no '/', just keep it as is, for example:
+3V3 would stay +3V3
This is useful when creating simplified testpoint lists in a large hierarchical schematic, where the path can get very long.

[Column List][Bom][Added] Added 'Net Label' column

---

docs/samples/generic_plot.kibot.yaml
docs/source/configuration/outputs/PanelizeFiducials.rst
kibot/out_panelize.py
tests/GUI/outputs
tests/GUI/stats

Adds `code` and `arg` options to support plugin type for fiducials in panelization.
See relevant [KiKit documentation](https://yaqwsx.github.io/KiKit/latest/panelization/cli/#plugin_5) for reference

Config: Panelize: Add missing fiducials plugin options

---

kibot/out_report.py

This PR adds the following to the report output:
- Allow changing number of digits for unit conversions
- Option to show trailing zeros
- Option to capitalize strings
- Access to Hole to Hole, Hole to Copper and Copper to Edge info (KiCad 6+)
- Access to PTH/NPTH specific drill dimensions
- Option to remove leading spaces/tabs after CSV separator (useful to generate CSV from a .txt template where elements are aligned for easier reading)

[Report][Added] Various new features

---

kibot/kicad/config.py

I was running into an issue where kibot was looking for 3d models in the 6.0 directory, but this directory didn't exist.
I ran into the issue on your container: ghcr.io/inti-cmnb/kicad_auto_full:dev_k8_1.8.3-6506638_k8.0.6_d_sid_b3.5.1

Use Kicad major version for 3dparty path

---

kibot/resources/tools/frame_plotter

This prevents an issue where the frame_plotter command would fail if e.g. `~/.config/kicad/8.0/colors/` did not exist. In CI using ghcr.io/inti-cmnb/kicad8_auto_full this manifests as:
ERROR:Running ['/usr/bin/python3', '/usr/share/kibot/tools/frame_plotter', '/tmp/tmp-kibot-pcb_print_tmp_pcb_for_frame-rcz7iz5p/PCB.kicad_pcb', '0.2823529411764706', '0.0', '0.0'] returned 1 (kibot.gs - gs.py:853)
Running the container manually and then running the above command shows the actual error messaged:
Traceback (most recent call last):
File "/usr/share/kibot/tools/frame_plotter", line 29, in <module> with tempfile.NamedTemporaryFile(mode='wt', delete=False, suffix='.json', prefix='kibo_color_', dir=path) as f:
[...]
FileNotFoundError: [Errno 2] No such file or directory: …

[Fixed] Let frame_plotter create colors directory if needed

---

kibot/out_any_drill.py
tests/yaml_samples/drill.kibot.yaml
tests/yaml_samples/drill_single.kibot.yaml

This PR fixes the overwriting of non through-hole drill pair files when `pth_id` is specified.
I've also modifed the YAML files for the test cases (non-legacy) so that the default `pth_id` and `npth_id` are explicitly specified. Without the fix, it will overwrite the files which results in the test failing.
I'm not sure how to modify the legacy YAML files for this test, I've tried to add `pth_id` and `npth_id` but doesn't seem to change anything, I assume the legacy way of generating drill files did not have a function to rename the files? In this case it would be a non-issue

[Any Drill][Fixed] Do not overwrite other drill pairs with pth_id

---

kibot/out_report.py
tests/data/report_output_path.txt
tests/reference/5_1_7/light_control-report_output_path_1.txt
tests/reference/5_1_7/light_control-report_output_path_2.txt
tests/reference/6_0_8/light_control-report_output_path_1.txt
tests/reference/6_0_8/light_control-report_output_path_2.txt
tests/reference/7_0_0/light_control-report_output_path_1.txt
tests/reference/7_0_0/light_control-report_output_path_2.txt
tests/reference/7_0_10/light_control-report_output_path_1.txt
tests/reference/7_0_10/light_control-report_output_path_2.txt
tests/reference/7_0_3/light_control-report_output_path_1.txt
tests/reference/7_0_3/light_control-report_output_path_2.txt
tests/reference/7_0_6/light_control-report_output_path_1.txt
tests/reference/7_0_6/light_control-report_output_path_2.txt
tests/reference/8_0_0/light_control-report_output_path_1.txt
tests/reference/8_0_0/light_control-report_output_path_2.txt
tests/test_plot/test_misc.py
tests/yaml_samples/report_output_path.kibot.yaml

This PR adds to the `report` output a new expansion pattern `${<output_name>_outpath_<index>}` (index optional, starts at 1), which returns the relative path between the generated report file and the output. This is useful for creating README files or other files that need a relative path to a specific file.
Example configuration:
https://github.com/nguyen-v/KiBot/blob/report_out_path/tests/yaml_samples/report_output_path.kibot.yaml
With this template:
https://github.com/nguyen-v/KiBot/blob/report_out_path/tests/data/report_output_path.txt
Generates:
https://github.com/nguyen-v/KiBot/blob/report_out_path/tests/reference/8_0_0/light_control-report_output_path_1.txt
https://github.com/nguyen-v/KiBot/blob/report_out_path/tests/reference/8_0_0/light_control-report_output_path_2.txt

[Report][Added] Expand relative paths to specific outputs

---

kibot/kicad/drill_info.py
kibot/out_any_drill.py
tests/board_samples/kicad_5/3Rs_bv.kicad_pcb
tests/test_plot/test_drill.py
tests/utils/context.py
tests/yaml_samples/drill.kibot.yaml
tests/yaml_samples/drill_legacy.kiplot.yaml
tests/yaml_samples/drill_legacy_s.kiplot.yaml
tests/yaml_samples/drill_single.kibot.yaml

This PR adds a CSV drill table output to the `excellon` output. I've added a simple test case in `test_drill.py`.
It's basically a reimplementation of
https://gitlab.com/kicad/code/kicad/-/blob/master/pcbnew/exporters/gendrill_file_writer_base.cpp
It should work for KiCad 5+, but for KiCad 5 the generated table is slightly different (because of missing attributes).
The column order/names can be changed similar to how it's done in bom.
Example from `drill.kibot.yaml`
```
kibot:
version: 1
outputs:
- name: excellon_drill
comment: "Excellon drill files"
type: excellon
dir: Drill
options:
metric_units: true
pth_and_npth_single_file: false
use_aux_axis_as_origin: false
minimal_header: false
mirror_y_axis: false
report: '%f-%i.%x'
map: 'pdf'
table:
pth_and_npth_single_file: false
- name: …
```

[Drill][Added] CSV Drill Table output

---

tests/test_plot/test_print_pcb.py

Just a small correction in the `@pytest.mark.skipif` statement

[PCB Print Tests][Fixed] Also include V9+ in drillmap tests

---

kibot/out_base.py

Update the mechanism to use MTEXT or PCB_TEXT attributes instead of just MTEXT. PCB_TEXT replaced MTEXT in kicad 7.

fix #818 (3D models): update 3D variant aspect mechanism to check for PCB_TEXT

---

kibot/out_base.py

- Correct logic to select default 3D slot selection (added `any_matched`)
- Renamed `default` to `default_slots` for clarity.
- Add debug logging for variant matching
- Apply default 3D models only if no variant matches

fix(out_base): update 3D variant aspect matching logic
